import 'package:medglobal_admin_portal/core/core.dart';

/// For simplicity, ID should always be the first column.
/// ID columns are hidden in the DataGrid display.
class DataGridColumn {
  static List<ColumnData> products = [
    ColumnData('id', 'ID'),
    ColumnData('name', 'Name', minWidth: 300.0),
    ColumnData('category', 'Category', minWidth: 180.0),
    ColumnData('createdAt', 'Created At', minWidth: 180.0),
  ];

  static List<ColumnData> suppliers = [
    ColumnData('id', 'ID'),
    ColumnData('name', 'Name', minWidth: 300.0),
    ColumnData('email', 'Email', minWidth: 200.0),
    ColumnData('phone', 'Phone', minWidth: 200.0),
  ];
  static List<ColumnData> branches = [
    ColumnData('id', 'ID'),
    ColumnData('name', 'Name', minWidth: 300.0),
    ColumnData('price', 'Price', minWidth: 200.0, isEditable: true),
    ColumnData('qtyOnHand', 'Qty on Hand', minWidth: 200.0, isEditable: true),
  ];

  static List<ColumnData> variants = [
    ColumnData('id', 'ID'),
    ColumnData('name', 'Variant', minWidth: 300.0),
    // ColumnData('sku', 'SKU', minWidth: 150.0),
    ColumnData('price', 'Price (PHP)', minWidth: 100.0),
    // ColumnData('cost', 'Cost (PHP)', minWidth: 100.0),
    // ColumnData('qtyOnHand', 'Qty On Hand', minWidth: 120.0),
    ColumnData('warningStock', 'Warning Stock Level', minWidth: 170.0),
    ColumnData('idealStock', 'Ideal Stock Level', minWidth: 150.0),
    ColumnData('suppliers', 'Suppliers', minWidth: 250.0),
    ColumnData('action', 'Action', minWidth: 100.0),
  ];

  static List<String> customs = ['action'];
}

/// MOCK DATA
// final productList = [
//   const ProductGrid(
//     id: 1,
//     name: 'Absolute Distilled Water 350 ML',
//     category: 'Food Supplement',
//     sku: 'ADW-350ML',
//     barcode: '',
//     cost: 20.00,
//     price: 30.00,
//     margin: 3,
//     qty: 40,
//   ),
//   const ProductGrid(
//     id: 2,
//     name: 'Absolute Distilled Water 350 ML',
//     category: 'Food Supplement',
//     sku: 'MG-B-0071-133.05MG',
//     barcode: '',
//     cost: 20.00,
//     price: 30.00,
//     margin: 3,
//     qty: 40,
//   ),
//   const ProductGrid(
//     id: 3,
//     name: 'Absolute Distilled Water 1000 ML',
//     category: 'Food Supplement',
//     sku: 'ADW-350ML',
//     barcode: '',
//     cost: 20.00,
//     price: 30.00,
//     margin: 3,
//     qty: 40,
//   ),
//   const ProductGrid(
//     id: 4,
//     name: 'Absolute Distilled Water 350 ML',
//     category: 'Food Supplement',
//     sku: 'ADW-350ML',
//     barcode: '',
//     cost: 20.00,
//     price: 30.00,
//     margin: 3,
//     qty: 40,
//   ),
//   const ProductGrid(
//     id: 5,
//     name: 'Absolute Distilled Water 350 ML',
//     category: 'Food Supplement',
//     sku: 'ADW-350ML',
//     barcode: '',
//     cost: 20.00,
//     price: 30.00,
//     margin: 3,
//     qty: 40,
//   ),
//   const ProductGrid(
//     id: 6,
//     name: 'Absolute Distilled Water 350 ML',
//     category: 'Food Supplement',
//     sku: 'ADW-350ML',
//     barcode: '',
//     cost: 20.00,
//     price: 30.00,
//     margin: 3,
//     qty: 40,
//   ),
//   const ProductGrid(
//     id: 7,
//     name: 'Absolute Distilled Water 350 ML',
//     category: 'Food Supplement',
//     sku: 'ADW-350ML',
//     barcode: '',
//     cost: 20.00,
//     price: 30.00,
//     margin: 3,
//     qty: 40,
//   ),
//   const ProductGrid(
//     id: 8,
//     name: 'Absolute Distilled Water 350 ML',
//     category: 'Food Supplement',
//     sku: 'ADW-350ML',
//     barcode: '',
//     cost: 20.00,
//     price: 30.00,
//     margin: 3,
//     qty: 40,
//   ),
//   const ProductGrid(
//     id: 9,
//     name: 'Absolute Distilled Water 350 ML',
//     category: 'Food Supplement',
//     sku: 'ADW-350ML',
//     barcode: '',
//     cost: 20.00,
//     price: 30.00,
//     margin: 3,
//     qty: 40,
//   ),
//   // const ProductGrid(
//   //   id: 10,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 11,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 12,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 13,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 14,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 15,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 16,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 17,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 18,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 19,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 20,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 21,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 22,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 23,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 24,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
//   // const ProductGrid(
//   //   id: 25,
//   //   name: 'Absolute Distilled Water 350 ML',
//   //   category: 'Food Supplement',
//   //   sku: 'ADW-350ML',
//   //   barcode: '',
//   //   cost: 20.00,
//   //   price: 30.00,
//   //   margin: 3,
//   //   qty: 40,
//   // ),
// ];

// class Product {
//   final String id;
//   final String name;
//   final String category;
//   final String sku;
//   final String barcode;
//   final String cost;
//   final String price;
//   final int margin;
//   final int qty;

//   const Product({
//     required this.id,
//     required this.name,
//     required this.category,
//     required this.sku,
//     required this.barcode,
//     required this.cost,
//     required this.price,
//     required this.margin,
//     required this.qty,
//   });

//   factory Product.fromJson(Map<String, dynamic> json) => Product(
//         id: json['id'],
//         name: json['name'],
//         category: json['category'],
//         sku: json['sku'],
//         barcode: json['barcode'],
//         cost: json['cost'],
//         price: json['price'],
//         margin: json['margin'],
//         qty: json['qty'],
//       );

//   @override
//   bool operator ==(Object other) =>
//       identical(this, other) ||
//       other is Product &&
//           runtimeType == other.runtimeType &&
//           id == other.id &&
//           name == other.name &&
//           category == other.category &&
//           sku == other.sku &&
//           barcode == other.barcode &&
//           cost == other.cost &&
//           price == other.price &&
//           margin == other.margin &&
//           qty == other.qty;

//   Map<String, dynamic> toMap() {
//     return {
//       'id': id,
//       'name': name,
//       'category': category,
//       'sku': sku,
//       'barcode': barcode,
//       'cost': cost,
//       'price': price,
//       'margin': margin,
//       'qty': qty,
//     };
//   }

//   RowData get toRowData => RowData(toMap());

//   dynamic get(String propertyName) {
//     return toMap()[propertyName].toString();
//   }
// }

// class SupplierTest {
//   final String id;
//   final String name;
//   final String mainContactName;
//   final String email;
//   final String phone;
//   final String fax;
//   final String website;
//   final String street1;
//   final String street2;
//   final String city;
//   final String state;
//   final String zipCode;
//   final String country;
//   final String createdAt;
//   final String updatedAt;

//   const SupplierTest({
//     required this.fax,
//     required this.website,
//     required this.street1,
//     required this.street2,
//     required this.city,
//     required this.state,
//     required this.zipCode,
//     required this.country,
//     required this.createdAt,
//     required this.updatedAt,
//     required this.id,
//     required this.name,
//     required this.mainContactName,
//     required this.email,
//     required this.phone,
//   });

//   factory SupplierTest.fromJson(Map<String, dynamic> json) => SupplierTest(
//         id: json['id'],
//         name: json['name'],
//         mainContactName: json['mainContactName'],
//         email: json['email'],
//         phone: json['phone'],
//         fax: json['fax'],
//         website: json['website'],
//         street1: json['street1'],
//         street2: json['street2'],
//         city: json['city'],
//         state: json['state'],
//         zipCode: json['zipCode'],
//         country: json['country'],
//         createdAt: json['createdAt'],
//         updatedAt: json['updatedAt'],
//       );

//   // @override
//   // bool operator ==(Object other) =>
//   //     identical(this, other) ||
//   //     other is SupplierTest &&
//   //         runtimeType == other.runtimeType &&
//   //         id == other.id &&
//   //         name == other.name &&
//   //         email == other.email &&
//   //         phone == other.phone;

//   Map<String, dynamic> toMap() {
//     return {
//       'id': id,
//       'name': name,
//       'email': email,
//       'phone': phone,
//     };
//   }

//   RowData get toRowData => RowData(toMap());

//   dynamic get(String propertyName) {
//     return toMap()[propertyName].toString();
//   }
// }

// final supplierList = [
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
//   const SupplierTest(
//       id: '1',
//       name: 'Ana Supermaket',
//       email: 'supplier@a.com',
//       phone: '432404242',
//       fax: '',
//       website: '',
//       street1: '',
//       street2: '',
//       city: '',
//       state: '',
//       zipCode: '',
//       country: '',
//       createdAt: '',
//       updatedAt: '',
//       mainContactName: ''),
// ];

// class Variant {
//   final String id;
//   final String variant;
//   final String sku;
//   final String price;
//   final String cost;
//   final int qtyOnHand;
//   final int warningStockLevel;
//   final int idealStockLevel;
//   final List<String> suppliers;

//   const Variant({
//     required this.id,
//     required this.sku,
//     required this.price,
//     required this.cost,
//     required this.variant,
//     required this.qtyOnHand,
//     required this.warningStockLevel,
//     required this.idealStockLevel,
//     required this.suppliers,
//   });

//   factory Variant.fromJson(Map<String, dynamic> json) => Variant(
//         id: json['id'],
//         variant: json['variant'],
//         sku: json['sku'],
//         price: json['price'],
//         cost: json['cost'],
//         qtyOnHand: json['qtyOnHand'],
//         warningStockLevel: json['warningStockLevel'],
//         idealStockLevel: json['idealStockLevel'],
//         suppliers: json['suppliers'],
//       );

//   @override
//   bool operator ==(Object other) =>
//       identical(this, other) ||
//       other is Variant &&
//           runtimeType == other.runtimeType &&
//           id == other.id &&
//           variant == other.variant &&
//           sku == other.sku &&
//           price == other.price &&
//           cost == other.cost &&
//           qtyOnHand == other.qtyOnHand &&
//           warningStockLevel == other.warningStockLevel &&
//           idealStockLevel == other.idealStockLevel &&
//           suppliers == other.suppliers;

//   Map<String, dynamic> toMap() {
//     return {
//       'id': id,
//       'variant': variant,
//       'sku': sku,
//       'price': price,
//       'cost': cost,
//       'qtyOnHand': qtyOnHand,
//       'warningStockLevel': warningStockLevel,
//       'idealStockLevel': idealStockLevel,
//       'suppliers': suppliers,
//     };
//   }

//   RowData get toRowData => RowData(toMap());

//   dynamic get(String propertyName) {
//     return toMap()[propertyName].toString();
//   }
// }

// final variantList = [
//   const Variant(
//     id: 1,
//     name: 'Variant A',
//     // sku: 'SGSD8732',
//     // cost: 20.00,
//     // qtyOnHand: 30,
//     warningStock: 10,
//     idealStock: 30,
//     suppliers: [156546554534, 2343645787798],
//   ),
//   const Variant(
//     id: 2,
//     name: 'Variant B',
//     // sku: 'SGSD8732',
//     // cost: 20.00,
//     // qtyOnHand: 30,
//     warningStock: 10,
//     idealStock: 30,
//     suppliers: [156546554534, 2343645787798],
//   ),
  // const Variant(
  //   id: '1',
  //   variant: 'Variant A',
  //   sku: 'SGSD8732',
  //   price: '32.00',
  //   cost: '20.00',
  //   qtyOnHand: 30,
  //   warningStockLevel: 10,
  //   idealStockLevel: 30,
  //   suppliers: ['Today Mart', 'Hello Grocery', 'Ayo Grocery'],
  // ),
  // const Variant(
  //   id: '1',
  //   variant: 'Variant A',
  //   sku: 'SGSD8732',
  //   price: '32.00',
  //   cost: '20.00',
  //   qtyOnHand: 30,
  //   warningStockLevel: 10,
  //   idealStockLevel: 30,
  //   suppliers: ['Go Go Supermarket', 'Today Mart', 'Hello Grocery', 'Yes! Mart', 'Ayo Grocery'],
  // ),
// ];
